spring:
  datasource:
    url: 'jdbc:mysql://localhost:3308/${PRISMA_DB_DATABASE_NAME}'
    username: '${PRISMA_DB_USERNAME}'
    password: '${PRISMA_DB_PASSWORD}'
  flyway:
    enabled: false
  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: src/main/resources/ddl_jpa_creation.sql
  config:
    activate:
      on-profile: generatesql