apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dev-github-actions-clusterrolebinding
  namespace: prisma
subjects:
- kind: ServiceAccount
  name: dev-github-actions-serviceaccount
  namespace: prisma
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dev-github-actions-clusterrole