#kubectl get serviceaccounts dev-github-actions-serviceaccount -o yaml -n prisma
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-github-actions-serviceaccount
  namespace: prisma
secrets:
- name: dev-github-actions-serviceaccount-secret