#kubectl get serviceaccounts prod-github-actions-serviceaccount -o yaml -n prisma-prod
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prod-github-actions-serviceaccount
  namespace: prisma-prod
secrets:
- name: prod-github-actions-serviceaccount-secret