# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
#
#
# "docker" job made with help from https://github.com/docker/build-push-action
#
#
name: Build and Publish Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 17
#Test
    - name: Test with Maven
      run: mvn -B test
#Build
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: RUNNING CUSTOM DEBUG INFO
      run: | 
        echo "PRINTING CUSTOM DEBUG INFO"
        pwd
        ls -a
        echo "========="
        find . -name 'HelloWorld-0.0.1-SNAPSHOT.jar'

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
# Docker
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: RUNNING CUSTOM DEBUG INFO 2
      run: | 
        echo "PRINTING CUSTOM DEBUG INFO 2"
        pwd
        ls -a
        echo "========="
        find . -name 'HelloWorld-0.0.1-SNAPSHOT.jar'

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push to DockerHub
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/java_helloworld:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
