# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
#
#
# "docker" job made with help from https://github.com/docker/build-push-action
#
#
name: RELEASE PIPELINE

on:
   release:
     types: [published]
# on:
#   push:
#     branches: [ main, dev , release-pipeline ]
#   pull_request:
#     branches: [ main, dev , release-pipeline ]

jobs:
  release-dev:
    #if: ${{ github.ref_name }} == 'dev'
    runs-on: ubuntu-latest
    steps:
#Checkout the repo, this sets up the environment and scans for all files.
    - uses: actions/checkout@v3
    - run: echo ${{ github.ref }}
    - run: echo ${{ github.ref_name }}
    - run: echo DEBUG TEST - DEV
      if: ${{ github.ref_name }} == 'dev'
  release-main:
    #if: ${{ github.ref_name }} == 'main'
    runs-on: ubuntu-latest
    steps:
#Checkout the repo, this sets up the environment and scans for all files.
    - uses: actions/checkout@v3
    - run: echo ${{ github.ref }}
    - run: echo ${{ github.ref_name }}
    - run: echo DEBUG TEST - MAIN
      if: ${{ github.ref_name }} == 'main'
