# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
#
#
# "docker" job made with help from https://github.com/docker/build-push-action
#
#
name: RELEASE PIPELINE

#on:
#   release:
#     types: [published]
on:
  push:
    branches: [ dev , release-pipeline ]
  pull_request:
    branches: [ dev , release-pipeline ]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
#Checkout the repo, this sets up the environment and scans for all files.
    - uses: actions/checkout@v3
    - run: echo ${{ github.ref }}
    - run: echo ${{ github.ref_name }}
    #- run: echo ${{ github.ref#refs/tags/ }}
    - run: echo HEADS
    - run: echo ${{ github.head_ref }}
    #- run: echo ${{ github.ref#refs/heads/ }}
    - run: git branch --show-current
    #- run: curl -L -X GET 'https://api.github.com/repos/JonathanVandenBoschPXL/Java_HelloWorld/tags' -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'
    # - run: export TOKEN=${{ secrets.GITHUB_TOKEN }}
    # - name: Run script file
    #   run: |
    #      chmod +x ./tagFixer.sh
    #      ./tagFixer.sh
    #   shell: bash
    # - run: curl -X GET 'https://api.github.com/repos/JonathanVandenBoschPXL/Java_HelloWorld/tags' -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }} -H "Accept: application/vnd.github+json"
    - uses: oprypin/find-latest-tag@v1
      name: get latest pre-release
      with:
        repository: JonathanVandenBoschPXL/Java_HelloWorld  # The repository to scan.
        releases-only: true  # We know that all relevant tags have a GitHub release for them.
        prefix: 'v'
        regex: '^[v]\d+\.\d+\.\d+(-pre)\d+$'
        sort-tags: true
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN_CLASSIC }}
      id: octokit  # The step ID to refer to later.
    - run: echo ${{ steps.octokit.outputs.tag }}
    - uses: oprypin/find-latest-tag@v1
      name: get latest release
      with:
        repository: PXL-PRiSMA/PRiSMA  # The repository to scan.
        releases-only: true  # We know that all relevant tags have a GitHub release for them.
        prefix: 'v'
        regex: '^[v]\d+\.\d+\.\d+$'
        sort-tags: true
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN_CLASSIC }}
      id: octokit2  # The step ID to refer to later.
    - run: echo ${{ steps.octokit2.outputs.tag }}
    - name: Create tag
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v0.0.6',
              sha: context.sha
            })
    - name: Create Release
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: v0.0.7,
              target_commitish: dev,
              name: 'just a release (v0.0.7)',
              body: 'test body',
              generate_release_notes: true
            });

      
