name: '[Manual] Non-functional Tests'
on: [workflow_dispatch]
jobs:
  example:
    name: Just a job
    runs-on: ubuntu-latest
    steps:
      - name: Run JMeter Tests
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: e2e/jmeter/testfile.jmx
          outputReportsFolder: e2e/jmeter/
      - name: list all outputs 
        run: ls -A ./e2e/jmeter/