name: '[Manual] Non-functional Tests'
on: [workflow_dispatch]
jobs:
  example:
    name: Just a job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: debug
        run: ls -A ./e2e/jmeter/
      # - name: Run JMeter Tests
      #   uses: rbhadti94/apache-jmeter-action@v0.6.0
      #   with:
      #     testFilePath: e2e/jmeter/testfile.jmx
      #     outputReportsFolder: e2e/jmeter/
      - name: JMeter Test
        uses: QAInsights/PerfAction@v3.1
        with:
          test-plan-path: ./e2e/jmeter/testfile.jmx
          args: "--loglevel INFO"
      - name: list all outputs 
        run: |
          ls -A 
          echo ==========================
          ls -A ./e2e/jmeter/