name: TEST FLOW

#on:
#   release:
#     types: [published]
on:
  push:
    branches: [ dev , release-pipeline ]
  pull_request:
    branches: [ dev , release-pipeline ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
#Checkout the repo, this sets up the environment and scans for all files.
    - run: echo test